name: advanced_components_and_theming
description: Work in progress, Demonstrations of expanding bottom sheet and backdrop choreography.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  scoped_model: 0.3.0
  shrine_images: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/diamond.png
  - assets/slanted_menu.png
  - packages/shrine_images/0-0.jpg
  - packages/shrine_images/1-0.jpg
  - packages/shrine_images/2-0.jpg
  - packages/shrine_images/3-0.jpg
  - packages/shrine_images/4-0.jpg
  - packages/shrine_images/5-0.jpg
  - packages/shrine_images/6-0.jpg
  - packages/shrine_images/7-0.jpg
  - packages/shrine_images/8-0.jpg
  - packages/shrine_images/9-0.jpg
  - packages/shrine_images/10-0.jpg
  - packages/shrine_images/11-0.jpg
  - packages/shrine_images/12-0.jpg
  - packages/shrine_images/13-0.jpg
  - packages/shrine_images/14-0.jpg
  - packages/shrine_images/15-0.jpg
  - packages/shrine_images/16-0.jpg
  - packages/shrine_images/17-0.jpg
  - packages/shrine_images/18-0.jpg
  - packages/shrine_images/19-0.jpg
  - packages/shrine_images/20-0.jpg
  - packages/shrine_images/21-0.jpg
  - packages/shrine_images/22-0.jpg
  - packages/shrine_images/23-0.jpg
  - packages/shrine_images/24-0.jpg
  - packages/shrine_images/25-0.jpg
  - packages/shrine_images/26-0.jpg
  - packages/shrine_images/27-0.jpg
  - packages/shrine_images/28-0.jpg
  - packages/shrine_images/29-0.jpg
  - packages/shrine_images/30-0.jpg
  - packages/shrine_images/31-0.jpg
  - packages/shrine_images/32-0.jpg
  - packages/shrine_images/33-0.jpg
  - packages/shrine_images/34-0.jpg
  - packages/shrine_images/35-0.jpg
  - packages/shrine_images/36-0.jpg
  - packages/shrine_images/37-0.jpg
  - assets/0.png
  - assets/1.png
  - assets/2.png
  - assets/3.png
  - assets/4.png
  - assets/5.png
  - assets/6.png
  - assets/logo.png
  - assets/person.png
  - assets/plane.png
  - assets/pin.png
  - assets/calendar.png
  - assets/hotel.png
  - assets/time.png
  - assets/food.png
  - assets/menu_logo.png
  - assets/logo.png
  - assets/thumb.png

  - assets/ic_arrow_back_24px.png
  - assets/ic_arrow_forward_ios_24px.png
  - assets/ic_attach_money_24px.png
  - assets/ic_bar_chart_24px.png
  - assets/ic_credit_card_24px.png
  - assets/ic_info_outline_24px.png
  - assets/ic_money_off_24px.png
  - assets/ic_not_interested_24px.png
  - assets/ic_pie_chart_24px.png
  - assets/ic_pie_chart_outlined_24px.png
  - assets/ic_search_24px.png
  - assets/ic_settings_24px.png
  - assets/ic_sort_24px.png
  - assets/logo_rally.png


  fonts:
  - family: Rubik
    fonts:
    - asset: fonts/Rubik-Regular.ttf
    - asset: fonts/Rubik-Medium.ttf
      weight: 500
  - family: Raleway
    fonts:
    - asset: fonts/Raleway-Regular.ttf
    - asset: fonts/Raleway-SemiBold.ttf
  - family: Roboto Condensed
    fonts:
      - asset: fonts/RobotoCondensed-Light.ttf
        weight: 400
      - asset: fonts/RobotoCondensed-Regular.ttf
        weight: 500
      - asset: fonts/RobotoCondensed-Bold.ttf
        weight: 700
  - family: Eczar
    fonts:
      - asset: fonts/Eczar-Regular.ttf
      - asset: fonts/Eczar-Bold.ttf
        weight: 500

